### ISSUE TITLE
socket is already open/closed

### ISSUE THREAD

**Issue by dantimofte** [Crypto-toolbox/btfxwss#127] opened 2018-03-30 07:42 UTC
Hello, 
I have a issue and i don't know how to approach it to find a fix. 
The logs look like this : 
![image](https://user-images.githubusercontent.com/4211982/38129239-e3bb5744-3406-11e8-9458-14f1cbfe1d84.png)

![image](https://user-images.githubusercontent.com/4211982/38129255-ee13c6ea-3406-11e8-8e9b-a5f6188f2353.png)

Did anyone hit this problem ? Any suggestions on how to fix it ?

Thank you

**Comment by nlsdfnbch** [comment] 2018-04-11 15:33
Hey @dantimofte ,
thanks for contributing!

This could be an issue with too many connection attempts - could you explain at what time you see this error or how to reproduce it ?

**Comment by dantimofte** [comment] 2018-04-11 15:48
Hello,

When installing the  library either with pip3 or python3 setup.py install it installs the latest version of websocket , when i had that error the latest was 0.47.0.

I had another environment that was stable where version 0.46.0 is installed. After replacing 0.47.0 with 0.46.0 the error did not come up again.

Regards

**Comment by nlsdfnbch** [comment] 2018-04-17 11:04
So this is a websocket version issue. I'll look into it, but it may be a while before I get to work on it. If anyone wants to pick this up, go ahead!

**Comment by scoupafi** [comment] 2018-06-08 07:21
Are there any updates on this?

**Comment by dantimofte** [comment] 2018-06-08 09:33
I don't know how to fix the installer to make sure it install a good version of websocket .

What i do is that I make sure i have a good version installed after installing btfxwss : 

pip3 uninstall websocket-client
pip3 install websocket-client==0.46.0

**Comment by AdmiralThrawn** [comment] 2018-06-08 10:32
Same error occurs with v0.48.0 of websocket-client as well. Going to try v0.46.0.

**Comment by scoupafi** [comment] 2018-06-08 10:34
This is also frustrating, because due to the way Btfxwss is built, I can't handle/except the exception during the runtime of my application.

**Comment by tr91** [comment] 2018-07-15 03:03
Having this exact same issue with the exact same errors in the same lines. 

(Is this related to [https://github.com/Crypto-toolbox/btfxwss/issues/125]) ? Not sure how to go about implementing the fix mentioned there.

**Comment by scoupafi** [comment] 2018-07-15 08:33
@tr91 : Check @dantimofte 's answer.

**Comment by petr-fedorov** [comment] 2018-07-20 08:24
I believe this issue might be fixed when [reset WebsocketApp.sock #450](https://github.com/websocket-client/websocket-client/pull/450) pull request is merged into [websocket-client](https://github.com/websocket-client/websocket-client). In the meantime  you can made [this change](https://github.com/websocket-client/websocket-client/pull/450/commits/f42f58745bedd2c6c164d216f6ece21273be418c) yourself - it is just one line to be added - and check whether it helps.

In Btfxwss [WebSocketConnection._connect() ](https://github.com/petr-fedorov/btfxwss/blob/42f00f0c78fb9962d47e6d24132a753b1823c54b/btfxwss/connection.py#L121) method uses  [the loop](https://github.com/petr-fedorov/btfxwss/blob/42f00f0c78fb9962d47e6d24132a753b1823c54b/btfxwss/connection.py#L146) to restart run_forever() that is similar to the loop exemplified in the pull request (copied here for clarity):

    def ws_on_message(ws, message):
        msg = json.loads(message)
        if msg.get("restart"):
            ws.close()

    wsapp = websocket.WebSocketApp(url, on_message=ws_on_message, ...)
    while True:
        wsapp.run_forever()

 [WebSocketConnection.reconnect()](https://github.com/petr-fedorov/btfxwss/blob/42f00f0c78fb9962d47e6d24132a753b1823c54b/btfxwss/connection.py#L109)  calls [socket.close()](https://github.com/petr-fedorov/btfxwss/blob/42f00f0c78fb9962d47e6d24132a753b1823c54b/btfxwss/connection.py#L119) that is supposed to be fixed by the pull request

**Comment by tr91** [comment] 2018-07-20 16:12
Thanks @petr-fedorov 

I'll try adding this line as per that pull request:
self.sock = None

**Comment by petr-fedorov** [comment] 2018-07-20 19:57
@tr91 Unfortunately it might not be enough - just checked myself and found that weboscket-client crashes in another place(s). I will investigate the issue further.

**Comment by tr91** [comment] 2018-07-21 11:33
@petr-fedorov Thanks. Yes I was just about to post an issue after adding that that I get this error instead:
![2018-07-21_201323](https://user-images.githubusercontent.com/41246263/43035146-ae245ed4-8d2d-11e8-8999-3fdbd40615cf.png)

**Comment by tr91** [comment] 2018-07-21 17:47
@petr-fedorov Thanks. I'll make amends to the btfxwss\connection.py file, and will restore the original websockets _app.py file :)

**Comment by tr91** [comment] 2018-07-30 18:49
@petr-fedorov Hey Petr, happy to say I've not had any more of such errors since I last posted 9 days ago. <3 Hope its permanent

**Closed** 2018-07-31 10:12 UTC
Labels: bug, help wanted

**Comment by tr91** [comment] 2018-08-02 04:26
![2018-08-02_142549](https://user-images.githubusercontent.com/41246263/43562471-1083d98e-9660-11e8-8b00-0ade43bf3001.png)
Uh oh issue cropped up again

**Comment by petr-fedorov** [comment] 2018-08-02 05:33
@tr91 I don't see that from the above screenshot.  `INFO:btfxwss.connection: Connection closed` is a normal message. Traceback is for KeyboardInterrupt exception - you shouldn install signal handler for SIGINT (Ctrl+C) like [this](https://stackoverflow.com/questions/1112343/how-do-i-capture-sigint-in-python)  to exit gracefully

**Comment by tr91** [comment] 2018-08-02 05:48
@petr-fedorov I pressed Ctrl+C when the screenshot was taken. Hence it was stuck at "connection closed' for over 4 hours

**Comment by petr-fedorov** [comment] 2018-08-02 06:27
@tr91 Most likely it is a different issue. You need to set BtfxWss log level to DEBUG. i.e.  `wss = BtfxWss(log_level=logging.DEBUG)` in order to see what will happen exactly before "Connection closed" message. You'd better save log messages to file - there will be a lot of them

**Comment by tr91** [comment] 2018-08-04 05:59
Got it thanks petr! Now to wait another week or two :D

**Comment by petr-fedorov** [comment] 2018-08-09 06:14
Have a look at #152

**Comment by Indiana3714** [comment] 2018-08-23 16:19
@petr-fedorov 
![2018-08-24_021445](https://user-images.githubusercontent.com/41246263/44538184-f6333a80-a743-11e8-852e-942b84c16579.png)
Had a look at 152 as well, will make the changes to the file I have based on your commits. Thanks a lot! (new to github) Is there an updated bundled version of all the files as per your updates?

**Comment by petr-fedorov** [comment] 2018-08-28 08:49
@tr91 Everything has been merged already - you can try to install the latest version

**Comment by NogbadTheBad1** [comment] 2018-11-01 15:34
> Hello,
> 
> When installing the library either with pip3 or python3 setup.py install it installs the latest version of websocket , when i had that error the latest was 0.47.0.
> 
> I had another environment that was stable where version 0.46.0 is installed. After replacing 0.47.0 with 0.46.0 the error did not come up again.
> 
> Regards

Worked for me. Thanks!
