### ISSUE TITLE
Connection is not reopening once closed

### ISSUE THREAD

**Issue by rafaelcapucho** [Crypto-toolbox/btfxwss#48] opened 2017-09-15 04:19 UTC
Hello @nlsdfnbch :)

Ok, It ran on my VPS, it worked directly for 26 hours, then it died.

```
[root@arch-production phoenixsystem]# cat test.log | grep wss
INFO:btfxwss.connection:Connection opened
DEBUG:btfxwss.client:_subscribe: {'event': 'subscribe', 'channel': 'ticker', 'symbol': 'BTCUSD'}
DEBUG:btfxwss.client:_subscribe: {'event': 'subscribe', 'channel': 'ticker', 'symbol': 'IOTUSD'}
DEBUG:btfxwss.client:_subscribe: {'event': 'subscribe', 'channel': 'ticker', 'symbol': 'ETHUSD'}
DEBUG:btfxwss.client:_subscribe: {'event': 'subscribe', 'channel': 'ticker', 'symbol': 'LTCUSD'}
INFO:btfxwss.queue_processor:Subscription succesful for channel ('ticker', 'BTCUSD')
INFO:btfxwss.queue_processor:Subscription succesful for channel ('ticker', 'IOTUSD')
INFO:btfxwss.queue_processor:Subscription succesful for channel ('ticker', 'ETHUSD')
INFO:btfxwss.queue_processor:Subscription succesful for channel ('ticker', 'LTCUSD')
INFO:btfxwss.connection:Connection closed    (26 hous later, I know by looking at the graph)
```

So, the problem still exists in `dev` since it didn't even try to reconnect this time.

It is represented by the last "missing part" of the following 30m graph:
![as](https://user-images.githubusercontent.com/163367/30466329-7838e286-99b3-11e7-8485-eac71a0852b2.png)

Are there any other info that might help you? Just let me know, Thanks!

**Comment by nlsdfnbch** [comment] 2017-09-15 05:26
Hey @rafaelcapucho !

I have a suspicion where this might stem from. Bitfinex refreshes their trading engine, which requires clients to pause all activity, and finally reconnect to the API. While this is, to my understanding, technically implemented already, it might be faulty.

Could you run your client again, until the connection fails? But this time, start it in debugging mode
(`BtfxWss(key, secret, log_level=logging.DEBUG)`)? That way it also shows the websocket debug messages in the log. If you can't, no worries - I'll let it run on the weekend and test it myself, it's just going to take a little longer to fix. :)

Thanks again for reporting this!

**Comment by rafaelcapucho** [comment] 2017-09-15 13:32
Hello @nlsdfnbch :)

I did it, some outputs after insert the Debug `level`, the logs: https://pastebin.com/raw/tVNcZLCN
It is growing fast!, 

I will let you know when it stops.
Thanks!

**Comment by nlsdfnbch** [comment] 2017-09-16 08:21
Hm - unfortunately, I'm not sure this is working correctly. It should be logging messages from the `websocket-client` App, which it appears to not do. Have you defined a logger in your code, somwhere outside of the class? 

I'll run a test on my machine now as well.

**Comment by rafaelcapucho** [comment] 2017-09-16 16:19
Yes, I have defined my `logger`.

```
[root@arch-production phoenixsystem]# cat cli.py 
#!/usr/bin/env python3
import logging
import click
from main import entry_point

logging.basicConfig(level=logging.DEBUG, filename='test.log')
logger = logging.getLogger('phoenix')
logger.addHandler(logging.StreamHandler())

@click.group()
@click.option('-v', 'verbosity', flag_value=logging.INFO)
@click.option('-vv', 'verbosity', flag_value=logging.DEBUG)
@click.pass_context
def main(ctx, verbosity):
    verbosity = verbosity if verbosity else logging.WARNING
    logger.setLevel(verbosity)

@main.command()
@click.pass_obj
def run(ctx_obj):
    entry_point()


if __name__ == '__main__':
    main()
```

It is running ok in the last 24 hours atm, no closed connections, just let me know if I can help you ;)

**Comment by nlsdfnbch** [comment] 2017-09-19 15:22
Hey @rafaelcapucho !
Any updates? My instance has been running for 4 days without an issue (3 reconnects, but nothing stuck). 
I have to move the test instance to another machine, but I'll leave it running for another week. Hopefully I've got it logged then.

**Comment by rafaelcapucho** [comment] 2017-09-19 17:03
hey @nlsdfnbch :)

yes, It died sometimes but it was able to recover:

```
INFO:btfxwss.connection:Connection opened
DEBUG:btfxwss.client:_subscribe: {'event': 'subscribe', 'channel': 'ticker', 'symbol': 'BTCUSD'}
DEBUG:btfxwss.client:_subscribe: {'event': 'subscribe', 'channel': 'ticker', 'symbol': 'IOTUSD'}
DEBUG:btfxwss.client:_subscribe: {'event': 'subscribe', 'channel': 'ticker', 'symbol': 'ETHUSD'}
DEBUG:btfxwss.client:_subscribe: {'event': 'subscribe', 'channel': 'ticker', 'symbol': 'LTCUSD'}
INFO:btfxwss.queue_processor:Subscription succesful for channel ('ticker', 'BTCUSD')
INFO:btfxwss.queue_processor:Subscription succesful for channel ('ticker', 'IOTUSD')
INFO:btfxwss.queue_processor:Subscription succesful for channel ('ticker', 'ETHUSD')
INFO:btfxwss.queue_processor:Subscription succesful for channel ('ticker', 'LTCUSD')
INFO:btfxwss.connection:Connection Error - Connection is already closed.
INFO:btfxwss.connection:Connection closed
INFO:btfxwss.connection:Attempting to connect again in 10 seconds.
INFO:btfxwss.connection:Connection opened
INFO:btfxwss.connection:_on_open(): Connection reconnected, re-subscribing..
INFO:btfxwss.queue_processor:Subscription succesful for channel ('ticker', 'BTCUSD')
INFO:btfxwss.queue_processor:Subscription succesful for channel ('ticker', 'IOTUSD')
INFO:btfxwss.queue_processor:Subscription succesful for channel ('ticker', 'ETHUSD')
INFO:btfxwss.queue_processor:Subscription succesful for channel ('ticker', 'LTCUSD')
INFO:btfxwss.connection:Connection closed
INFO:btfxwss.connection:Attempting to connect again in 10 seconds.
INFO:btfxwss.connection:Connection opened
INFO:btfxwss.connection:_on_open(): Connection reconnected, re-subscribing..
INFO:btfxwss.queue_processor:Subscription succesful for channel ('ticker', 'BTCUSD')
INFO:btfxwss.queue_processor:Subscription succesful for channel ('ticker', 'IOTUSD')
INFO:btfxwss.queue_processor:Subscription succesful for channel ('ticker', 'ETHUSD')
INFO:btfxwss.queue_processor:Subscription succesful for channel ('ticker', 'LTCUSD')
INFO:btfxwss.connection:Connection Error - Connection is already closed.
INFO:btfxwss.connection:Connection closed
INFO:btfxwss.connection:Attempting to connect again in 10 seconds.
INFO:btfxwss.connection:Connection opened
INFO:btfxwss.connection:_on_open(): Connection reconnected, re-subscribing..
INFO:btfxwss.queue_processor:Subscription succesful for channel ('ticker', 'BTCUSD')
INFO:btfxwss.queue_processor:Subscription succesful for channel ('ticker', 'IOTUSD')
INFO:btfxwss.queue_processor:Subscription succesful for channel ('ticker', 'ETHUSD')
INFO:btfxwss.queue_processor:Subscription succesful for channel ('ticker', 'LTCUSD')
```

> I have to move the test instance to another machine, but I'll leave it running for another week. 
> Hopefully I've got it logged then.

Yeah, hopefully, thank for all your effort.
Cya!

**Comment by rafaelcapucho** [comment] 2017-09-21 04:35
Hello @nlsdfnbch 

Yes, It closed the connection...earlier today I restarted the system to load newer version of my project, it was working and now I saw that it had stopped some hours later:

```
DEBUG:btfxwss.client:_subscribe: {'event': 'subscribe', 'channel': 'ticker', 'symbol': 'BTCUSD'}
DEBUG:btfxwss.client:_subscribe: {'event': 'subscribe', 'channel': 'ticker', 'symbol': 'IOTUSD'}
DEBUG:btfxwss.client:_subscribe: {'event': 'subscribe', 'channel': 'ticker', 'symbol': 'ETHUSD'}
DEBUG:btfxwss.client:_subscribe: {'event': 'subscribe', 'channel': 'ticker', 'symbol': 'LTCUSD'}
DEBUG:btfxwss.client:_subscribe: {'event': 'subscribe', 'channel': 'ticker', 'symbol': 'OMGUSD'}
DEBUG:btfxwss.client:_subscribe: {'event': 'subscribe', 'channel': 'ticker', 'symbol': 'XMRUSD'}
DEBUG:btfxwss.client:_subscribe: {'event': 'subscribe', 'channel': 'ticker', 'symbol': 'ZECUSD'}
DEBUG:btfxwss.client:_subscribe: {'event': 'subscribe', 'channel': 'ticker', 'symbol': 'DSHUSD'}
INFO:btfxwss.queue_processor:Subscription succesful for channel ('ticker', 'BTCUSD')
INFO:btfxwss.queue_processor:Subscription succesful for channel ('ticker', 'IOTUSD')
INFO:btfxwss.queue_processor:Subscription succesful for channel ('ticker', 'ETHUSD')
INFO:btfxwss.queue_processor:Subscription succesful for channel ('ticker', 'LTCUSD')
INFO:btfxwss.queue_processor:Subscription succesful for channel ('ticker', 'OMGUSD')
INFO:btfxwss.queue_processor:Subscription succesful for channel ('ticker', 'XMRUSD')
INFO:btfxwss.queue_processor:Subscription succesful for channel ('ticker', 'ZECUSD')
INFO:btfxwss.queue_processor:Subscription succesful for channel ('ticker', 'DSHUSD')
INFO:btfxwss.connection:Connection closed
```

30min chart bellow, we can see it worked for days:
![graph](https://user-images.githubusercontent.com/163367/30679066-10e936c6-9e6d-11e7-9533-1f6fd1c75ee8.png)

Cya!

**Comment by nlsdfnbch** [comment] 2017-10-04 07:50
I'm still on this, but thus far cannot figure out the problem. The logs aren't helping, unfortunately. 

You may include a work-around in your code that, if no data is present in the queue, simply reconnect to the API manually. It's a dirty, quick fix and I'm not proud to suggest it - but it's perhaps the easiest solution for now!

**Comment by rafaelcapucho** [comment] 2017-10-05 00:42
Hi @nlsdfnbch !!

Yes, were you at least able to see the problem happening once with your own eyes?

My fast way to deal with it was to separate the script (that was running in a thread initially) to it own file and restart it using a `cronjob` each 5min, certainly it isn't even near to an elegant solution, as you said :) but it the way to go considering I have to keep the system running atm.

Bis bald mein freund :)

**Comment by nlsdfnbch** [comment] 2017-10-05 08:14
I have seen it indeed (you're not crazy,  after all :D) but i haven't found out why it does that.  At some point the connection just drops and doesn't reconnect. Its quite odd behaviour. I'll let you know as soon as I've fixed it though! Thanks again for the contribution!

**Comment by nlsdfnbch** [comment] 2017-11-08 08:16
@rafaelcapucho , I just pushed a fix for the resubscribe() method, which was related to #74, but may be the root cause for this problem. There was an error in the `resubscribe` method, which caused it to not work. This may be what's happening in this scenario. 
 Care to see if this fixed the issue? 

Cheers,
Nils

**Comment by rafaelcapucho** [comment] 2017-11-11 00:26
@nlsdfnbch buddy!

Hey, so I see you have good news :)
Right now I had to pause the development of this platform a bit, we need to retest the strategy a bit before continue, so I can't test it right now.
I hope to continue the project soon, I will be glad to test it again when possible and give you a feedback.

Thanks for all your effort and time,
reach me anytime,
Cheers,
Rafael.

**Closed** 2018-01-29 12:05 UTC
Labels: bug, help wanted
