### ISSUE TITLE
Dealing with [Errno 104] Connection reset by peer ?

### ISSUE THREAD

**Issue by Leobouloc** [Crypto-toolbox/btfxwss#112] opened 2018-01-12 19:24 UTC
I use this package to connect to regularly fetch orderbooks (fetching 7 pairs consecutively every 30 seconds). I usually encounter the following error after several minutes:

```
[Errno 104] Connection reset by peer 
```

The log then shows the repetition of the following lines (indefinitely):
```
INFO:btfxwss.connection:Connection closed
INFO:btfxwss.connection:Attempting to connect again in 10 seconds.
INFO:btfxwss.connection:Connection opened
INFO:btfxwss.connection:Connection closed
INFO:btfxwss.connection:Attempting to connect again in 10 seconds.
INFO:btfxwss.connection:Connection opened
...
```
The API works fine when I close the connection and re-instanciate `BtfxWss`.

As these errors are not raised, I cannot catch them. I have the following questions:
- Is the repeated "Attempting to connect" the intended behavior (is it normal that it does not connect when closing and re-instantiating works fine)?
- Is there a way to catch this error (a variable in the `wss` object), so that add the close/re-instantiate logic to my code when this happens?

**Comment by nlsdfnbch** [comment] 2018-01-13 06:17
Hey @Leobouloc  ,
Its hard to tell with what you've given me,  but generally yes - if the connection is reset,  the `Connection` object will try indefinitely to reconnect. There currently is no way to check this directly from the client (although you could check the is_connected attribute, but that's not really efficient). 
I can add a `max_retries` attribute to stop the connection from reconnecting infinitely. 

Could you provide the log with `DEBUG` log level set? Perhaps there's a programmatical error causing this. 

Cheers, 
Nils

**Comment by Leobouloc** [comment] 2018-01-15 20:56
Hey @nlsdfnbch. I logged this at `DEBUG` but there are no more logs than those that I provided above.. 

I'll look into using `_connected` as a temporary fix. 

Adding `max_retries`, wouldn't really help here; with the current behavior, I would rather have the error raised as soon as the connection is lost, but I suspect there is an problem with the re-connection feature since I am able to connect to the API by creating a new instance of `BtfxWss`. Let me know if there are other information I can provide to help diagnose the issue...

As a side question: when reconnecting, should I expect to receive a `snapshot`  or an `update` response?

Thank you!
Leo

**Comment by nlsdfnbch** [comment] 2018-01-15 21:20
>As a side question: when reconnecting, should I expect to receive a snapshot or an update response?
It should be a full snapshot - it essentially opens an entirely new session with Bitfinex.

>I would rather have the error raised as soon as the connection is lost

Well, setting `max_retries=0` would raise the error directly

>Let me know if there are other information I can provide to help diagnose the issue...
Thanks, that's much appreciated! I'll let you know as soon as I get time to properly look into this!

**Comment by Leobouloc** [comment] 2018-01-27 17:07
I haven't been able to reproduce this error for some time; not sure what was going on...

**Comment by nlsdfnbch** [comment] 2018-01-29 12:04
This may be due to too many connects - might have been that you've restarted the client too many times over a short period ? Eitherway, since it's not reproducable, I'll close this.

cheers!

**Closed by nlsdfnbch** 2018-01-29 12:04 UTC
Labels: bug, enhancement

**Comment by JinnyWang0716** [comment] 2018-08-02 06:58
I meet the same error(1006:java.io.IOException: Connection reset by peer) as you, when I reconnect, then throw DeploymentException(The HTTP response from the server [HTTP/1.1 200 OK] did not permit the HTTP upgrade to WebSocket). I don't know how to solve the problem, How do you solve it?

**Comment by JinnyWang0716** [comment] 2018-08-02 07:07
I know you create a new instance to solve the problem, thanks!
